# Changes here will be overwritten by Copier
_commit: v0.4.0-3-g8ce4890
_src_path: ..\linkml-project-copier
add_example: true
copyright_year: '2025'
email: david.linke@catalysis.de
full_name: David Linke
gh_action_docs_preview: true
gh_action_pypi: true
github_org: dalito
license: MIT
project_description: Test instance of linkml-copier-template.
project_name: test-linkml-project-copier
project_slug: test_linkml_project_copier
