---
site_name: "test-linkml-project-copier"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
exclude_docs: |
  /templates-linkml/
site_url: https://dalito.github.io/test-linkml-project-copier
repo_url: https://github.com/dalito/test-linkml-project-copier

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
