---
name: Deploy docs
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a gh-pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # allow to generate an OpenID Connect (OIDC) token

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0  # otherwise, you will fail to push refs to dest repo

      - name: Configure git for the bot
        # Gives the bot that commits to gh-pages a name & email address
        # so that the commits have an author in the commit log.
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182
        with:
          python-version: 3.12
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: 3.12

      - name: Install just
        run: |
          uv tool install rust-just

      - name: Install dependencies
        run: uv sync --dev --no-progress

      - name: Generate schema documentation
        run: |
          just gen-doc
          uv run mkdocs gh-deploy
