name: Preview documentation build

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:  preview-${{ github.ref }}

permissions: {}

jobs:
  run:
    # Grant GITHUB_TOKEN the permissions required to make a gh-pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # allow to generate an OpenID Connect (OIDC) token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: 3.9

      - name: Install poetry incl. plugins
        # We install poetry-dynamic-versioning into pipx because the automatic
        # install by poetry 2.x triggers a Windows issue
        # https://github.com/pypa/installer/issues/260
        # and also does not work on Ubuntu in gh-actions.
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Install dependencies
        run: poetry install

      - name: Build documentation
        run: |
          poetry run mkdocs build -d site
          touch site/.nojekyll

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@df22037db54ab6ee34d3c1e2b8810ac040a530c6
        with:
          source-dir: site/
          preview-branch: gh-pages
